server:
  port: 3306
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookcrawler?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update