insert into t_tabuaclubmember values (1,null,'F60WMT',null,null,'BEI/RONGHUA','brhsp123',null,null);
insert into t_tabuaclubmember values (2,null,'LRSKM3',null,null,'CHEN/CANYAN','ccytbid123',null,null);
insert into t_tabuaclubmember values (3,null,'CWVLWD',null,null,'CHOU/YAT MING','cymtb123',null,null);
insert into t_tabuaclubmember values (4,null,'DCRHBQ',null,null,'DU/JINSHENG','djstb123',null,null);
insert into t_tabuaclubmember values (5,null,'Q1BW7T',null,null,'CHAND/RAJESH','drtb123',null,null);
insert into t_tabuaclubmember values (6,null,'HDF66J',null,null,'FENG/PEILIAN','fpltb123',null,null);
insert into t_tabuaclubmember values (7,null,'XC2QTM',null,null,'HUNG/JIEYAU','hjy123',null,null);
insert into t_tabuaclubmember values (8,null,'WW1JCN',null,null,'HUANG/LIQING','hlqtb123',null,null);
insert into t_tabuaclubmember values (9,null,'XRMT3G',null,null,'JIA/JIN','jjtb123',null,null);
insert into t_tabuaclubmember values (10,null,'VK48KW',null,null,'KAN/FENGJINYE','kfjytb123',null,null);
insert into t_tabuaclubmember values (11,null,'H7KDHB',null,null,'KAN/SANLOK','ksltb123',null,null);
insert into t_tabuaclubmember values (12,null,'0NR44K',null,null,'CHONG/KWONG FAI SAMUEL','KWONG1969',null,null);
insert into t_tabuaclubmember values (13,null,'G07X78',null,null,'LI/HAOLIN','lhltb123',null,null);
insert into t_tabuaclubmember values (14,null,'CVWGPM',null,null,'LIANG/LIHUA','llhtb123',null,null);
insert into t_tabuaclubmember values (15,null,'S4F09J',null,null,'LI/XIAOYUN','lxytb123',null,null);
insert into t_tabuaclubmember values (16,null,'RQ511S',null,null,'LI/YUE','lye123',null,null);
insert into t_tabuaclubmember values (17,null,'0ZHVNP',null,null,'PHUA/SWEESENG','pstc123',null,null);
insert into t_tabuaclubmember values (18,null,'SW4W4L',null,null,'SHI/QINFANG','sqftb123',null,null);
insert into t_tabuaclubmember values (19,null,'P7QZSZ',null,null,'SUN/WENBIN','swbtb123',null,null);
insert into t_tabuaclubmember values (20,null,'DFX84C',null,null,'ZHAO/FULI','tcfl123',null,null);
insert into t_tabuaclubmember values (21,null,'KTVHGR',null,null,'HE/YONGJU','tchyj123',null,null);
insert into t_tabuaclubmember values (22,null,'82DKT6',null,null,'TAN/CHUNKIAM','tcktb123',null,null);
insert into t_tabuaclubmember values (23,null,'JQS3ZV',null,null,'ZHAO/MING','tczm123',null,null);
insert into t_tabuaclubmember values (24,null,'RKX0WQ',null,null,'WANG/YUEHUA','wyhtc123',null,null);
insert into t_tabuaclubmember values (25,null,'ZPSFZF',null,null,'YIP FUNG KWAI','yfktb123',null,null);
insert into t_tabuaclubmember values (26,null,'FJZSQ0',null,null,'YE/SANFA','ysftb123',null,null);
insert into t_tabuaclubmember values (27,null,'FRWVZ6',null,null,'ZHANG/YIFENG','ZYFTB123',null,null);
insert into t_tabuaclubmember values (28,null,'N8FLWF',null,null,'ZHENG/ZIYI  ','zzytc123',null,null);
insert into t_tabuaclubmember values (29,null,'PD7C5M',null,null,'LI/DONGMEI','ldmtb123',null,null);
